apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - rbac.yaml
  - crossplane-providers.yaml

helmCharts:
  - name: crossplane
    releaseName: crossplane
    version: 1.19.0
    repo: https://charts.crossplane.io/stable
    valuesFile: crossplane-values.yaml
    namespace: crossplane-system
    includeCRDs: true
